### ISSUE TITLE
config.ini.erb key sort issue

### ISSUE THREAD

**Issue by doomnuggets** [voxpupuli/puppet-grafana#10]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.1
- Ruby: 2.0.0
- Hiera: 3.2.2
- Distribution: CentOS 7
- Module version:  08600088845c4a8daa6426392ca94334790517b8 (customized)

## How to reproduce (e.g Puppet code you use)

Provide `grafana::cfg` with the following example data through `hiera`:

```yaml
grafana::cfg:
    app_mode: 'production'
    server:
        protocol: 'http'
        http_addr: '127.0.0.1'
        http_port: 3000
        domain: '192.168.0.34'
        enforce_domain: true
        root_url: '%(protocol)s://%(domain)s/grafana'
    analytics:
        reporting_enabled: false
        check_for_updates: false
    'basic.auth':
        enabled: false
```

## What are you seeing

The contents of `/etc/grafana/grafana.ini`:

```ini
[analytics]
check_for_updates = false
reporting_enabled = false
app_mode = production         <------- this line is misplaced

[basic.auth]
enabled = false

[server]
domain = 192.168.0.34
enforce_domain = true
http_addr = 127.0.0.1
http_port = 3000
protocol = http
root_url = %(protocol)s://%(domain)s/grafana
```

## What behaviour did you expect instead

The misplaced line should be located at the top of the file, not under the `[analytics]` section.

## Any additional information you'd like to impart

This can easily be fixed by **not** sorting the keys beforehand.
The sorting of the keys was introduced by this commit: 6df14d4e994f3825681b335ec6066fcdd6ee3ef2#L3
