### ISSUE TITLE
LDAP configurationf ile

### ISSUE THREAD

**Issue by pietjepuk111** [voxpupuli/puppet-grafana#313]
-->

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v6
- Ruby: 
- Distribution: rhel8
- Module version: latest

## How to reproduce (e.g Puppet code you use)

I have configured ldap in hiera style:
```
gdn_grafana::ldap:
  servers:
      host: ldap.test.lan
      port: 389
      bind_dn: 'secret'
      bind_password: '%{lookup("secrets::sa_ldap_grafana")}'
      search_filter: "(sAMAccountName=%s)"
      search_base_dns: 
  servers.attributes:
      member_of: memberOf
      email: email
  servers.group_mappings:
      group_dn: 'secret'
      org_role: "Admin"
      grafana_admin: true
```

## What are you seeing

The grafana ldap toml configuration file is not valid. The first server block is [servers] and should be [[servers]
This is the same for [servers.group_mappings], it should be [[servers.group_mappings]].

## What behaviour did you expect instead
```
[[servers]] instead of [servers] 
[[servers.group_mappings]] instead of 

[[servers]]
bind_dn = example
bind_password = "
host = example
port = 389
search_base_dns = xample
search_filter = "xample

[servers.attributes]
email = "email"
member_of = "memberOf"

[[servers.group_mappings]]
grafana_admin = true
group_dn = "CN=gdn-ict-beheer,OU=SecurityGroups,OU=Groups,OU=gdnnet,DC=gdnnet,DC=lan"
org_role = "Admin"

```
## Any additional information you'd like to impart

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/ldap/
